version: 0.0
os: linux
files:
  - source: /spring-project
    destination: /home/ubuntu/spring-project
permissions:
  - object: /home/ubuntu/spring-project
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: spring-project/scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu
